### ISSUE TITLE
vkCreateDevice失败

### ISSUE THREAD

**Issue by ADExxxxxx** [flwmxd/LuxGI#2]
VulkanDevice.cpp文件中第358行
`cpp
VK_CHECK_RESULT(vkCreateDevice(*physicalDevice, &deviceCreateInfo, VK_NULL_HANDLE, &device)); 
` 
报错 ERROR_EXTENSION_NOT_PRESENT，请问是硬件或者版本问题吗

**Comment by flwmxd** [comment]
what is your GPU model ?

**Comment by ADExxxxxx** [comment]
GTX1080，是必须图灵架构以上吗

**Comment by flwmxd** [comment]
理论上GTX1080 是没问题的，不管建议最好关闭掉光线追踪试试，或者升级你的显卡驱动。
