### ISSUE TITLE
Cmake error

### ISSUE THREAD

**Issue by HMar2022** [flwmxd/LuxGI#4]
CMake Error at Maple/lib/tracer/src/CMakeLists.txt:89 (set_target_properties):
  set_target_properties called with incorrect number of arguments.

**Comment by LazyWaves** [comment]
Same problem for me.

-- Could NOT find LibUnwind (missing: LibUnwind_INC LibUnwind_LIB)
-- Could NOT find LibELF (missing: LibELF_INC LibELF_INC2 LibELF_DW_LIB LibELF_ELF_LIB)
-- Could NOT find DLFCN (missing: DLFCN_INC DLFCN_DW_LIB)
-- Could NOT find LibBFD (missing: LibBFD_INC LibBFD_DW_LIB DLFCN_FOUND LibBFD_LIBZ LibBFD_LIBIBERTY)
-- Could NOT find DLFCN (missing: DLFCN_INC DLFCN_DW_LIB)
-- Could NOT find Execinfo (missing: Execinfo_INC Execinfo_LIB DLFCN_FOUND)
-- Could NOT find DLFCN (missing: DLFCN_INC DLFCN_DW_LIB)
-- Could NOT find Execinfo (missing: Execinfo_INC Execinfo_LIB DLFCN_FOUND)
fatal: not a git repository (or any of the parent directories): .git
CMake Error at Maple/lib/tracer/cmake/cmakeBuildTools/git.cmake:45 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.
Call Stack (most recent call first):
  Maple/lib/tracer/CMakeLists.txt:161 (run_git)

**Comment by crossous** [comment]
Don't download zip, i fetch it use github desktop to fix it.
Maybe it has some submodule at /Code/Maple/lib/tracer

**Comment by flwmxd** [comment]
you have to clone the project recursively
